Aggregate time span
DaveSkender/Stock.Indicators pull request #554
Opened 2021-09-06 20:01 UTC by heavymanto

- [ X] My code follows the existing style, code structure, and naming taxonomy
- [X ] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings and running code analysis does not produce any issues
- [X ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] New and existing unit tests pass locally and in the build (below) with my changes

2021-09-06 20:20 UTC, DaveSkender commented
@heavymanto, please restore the description of this PR to include the acknowledgment section.  You’ll have to check those boxes to indicate you understand what it means to contribute.  You cam get it here: .github/PULL_REQUEST_TEMPLATE.md

2021-09-06 21:42 UTC, DaveSkender requested changes
A few things to fix:

- [x] Add full unit test here: `tests/indicators/_Common/Test.QuoteHistory.cs`.  You only tested the external interface.
- [x] Restore the PR checklist in your description (see prior comment)
- [ ] Once you've done that, I'll add some changes to your branch to update documentation

2021-09-06 21:42 UTC, DaveSkender commented on src/_Common/Functions.cs
> +        internal static PeriodSize? ToPeriodSize(this TimeSpan timeSpan)
I suspect we no longer need this converter, right?  Suggest deleting it.

2021-09-06 21:42 UTC, DaveSkender commented on src/_Common/Quotes/Quotes.Functions.cs
> +            TimeSpan newPeriod)
I'd call this `timeSpan` instead of `newPeriod` to be clear on what it is.

2021-09-06 21:42 UTC, DaveSkender commented on src/_Common/Quotes/Quotes.Functions.cs
> +                    "Historical quotes Aggregation must use a New Size value of at least " +
Does `TimeSpan` support `<=` comparators?  If so, we should validate here to make sure it's greater than `TimeSpan.Zero` + adjust the message in this Exception.  I can modify this if you're not comfortable with writing it.

2021-09-06 21:42 UTC, DaveSkender commented on tests/indicators/_Common/Test.Functions.cs
> +        public void ToPeriodSize()
Won't need this if we also don't need this function.

2021-09-10 22:27 UTC, DaveSkender commented
@heavymanto I'd like to close and merge this PR in the next couple days, can you rebase and take a look at the issues to resolve in the comments above?

2021-09-11 11:42 UTC, heavymanto commented
Sorry for the delay. I've had a lot of work to do. I hope my changes are to your liking.

2021-09-11 19:29 UTC, DaveSkender commented
> Sorry for the delay. I've had a lot of work to do. I hope my changes are to your liking.

Looks pretty good to me.  I'll commit a few small items to your branch then merge it (mostly updating docs).
Thank you for your contribution!

2021-09-11 21:41 UTC, DaveSkender approved these changes

2021-09-11 22:02 UTC, merged